AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  MessageQueue:
    Type: AWS::SQS::Queue

  MessageProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskFailure
                - states:SendTaskSuccess
              Resource: !GetAtt StateMachine.Arn
      Events:
        PollQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MessageQueue
      DefinitionUri: ./stateMachine.yaml
